vault:
    image: vault:0.9.1
    ports:
    - "8200:8200"
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID=token
    cap_add:
    - IPC_LOCK
zookeeper:
     image: zookeeper
     ports:
     - "2181:2181"
     volumes:
     - /tmp/zookeeper/data:/data
     - /tmp/zookeeper/datalog:/datalog
mesosmaster:
     image: mesosphere/mesos-master:1.7.0
     ports:
     - "5050:5050"
     links:
     - zookeeper:zk
     environment:
     - MESOS_ZK=zk://zk:2181/mesos
     - MESOS_LOG_DIR=/var/log/mesos
     - MESOS_QUORUM=1
     - MESOS_REGISTRY=in_memory
     - MESOS_WORK_DIR=/var/lib/mesos
     - MESOS_HOSTNAME=localhost
     - MESOS_AUTHENTICATE_HTTP_FRAMEWORKS=true
     - MESOS_HTTP_FRAMEWORK_AUTHENTICATORS=basic
     - MESOS_CREDENTIALS=/etc/mesos/credentials
     volumes:
     - ./credentials:/etc/mesos/credentials
mesosslave:
     image: mesosphere/mesos-slave:1.7.0
     ports:
     - "5051:5051"
     links:
      - zookeeper:zk
      - mesosmaster:master
     entrypoint: mesos-slave
     privileged: true
     environment:
     - MESOS_MASTER=zk://zk:2181/mesos
     - MESOS_LOG_DIR=/var/log/mesos
     - MESOS_LOGGING_LEVEL=INFO
     - MESOS_WORK_DIR=/var/lib/mesos
     - MESOS_SYSTEMD_ENABLE_SUPPORT=false
     - MESOS_CONTAINERIZERS=docker,mesos
     volumes:
     - /var/run/docker.sock:/var/run/docker.sock
